adobe/helix-html-pipeline

package-lock.json, src/steps/extract-metadata.js, src/steps/folder-mapping.js, src/steps/utils.js, src/utils/path.js, test/steps/utils.test.js, test/utils/path.test.js
=> feat: avoid node built-ins (path and url)

src/html-pipe.js, test/html-pipe.test.js
=> fix: handling invalid input url with 400

src/utils/path.js, test/utils/path.test.js
=> fix: reject double-slashes

src/PipelineState.d.ts, src/PipelineState.js, src/forms-pipe.js, src/index.d.ts, src/index.js, src/options-pipe.js, test/forms-pipe.test.js, test/options-pipe.test.js
- adds handler for `OPTIONS` requests
- adds handler for `POST` requests
=> feat: provide pipes for OPTIONS and POSTs

src/steps/utils.js
=> fix: expect spec-compliant URL

src/PipelineState.d.ts, src/PipelineState.js, src/forms-pipe.js, src/html-pipe.js, src/json-pipe.js, src/steps/fetch-metadata.js, test/json-pipe.test.js
ignore last-modified header from metadata.json for json-pipeline
=> fix: correct last-modified handling for json

src/steps/fetch-config.js, src/steps/folder-mapping.js, src/steps/render.js, test/steps/fetch-config.test.js
fixes #36 
also see https://github.com/adobe/helix-admin/pull/557
=> feat: adjust for upcoming helix-config changes

src/index.d.ts, src/steps/extract-metadata.js, src/steps/folder-mapping.js, src/utils/path.js, test/fixtures/content/metadata.json, test/rendering.test.js, test/utils/path.test.js
Fixes glob matching for mapped pages
fixes #69
=> fix: Match globs for mapped pages

package-lock.json, src/steps/set-x-surrogate-key-header.js, test/rendering.test.js
=> fix: add metadata and head surrogate keys also on .plain

package-lock.json, src/steps/set-x-surrogate-key-header.js, test/rendering.test.js
=> fix: add metadata and head surrogate keys also on .plain (#108)

src/utils/auth.js
=> fix: make auth portable

src/utils/auth.js
=> fix: auth on non-node runtime

.eslintrc.cjs, package-lock.json, package.json, src/steps/parse-markdown.js, src/utils/mdast-to-hast.js, test/fixtures/content/page-with-gridtables.html, test/fixtures/content/page-with-gridtables.md, test/rendering.test.js
- enables gridtable parsing and image-references resolution.
=> feat: parse gridtables

package-lock.json, package.json, src/utils/auth.js, src/utils/crypto.node.js, src/utils/crypto.worker.js
=> feat: improve cross platform compatibilty with conditional crypto import

src/html-pipe.js, test/rendering.test.js
=> fix(html): do not skip custom headers for 3xx responses

src/steps/utils.js, test/steps/utils.test.js
Some link rewriting issues:
- / is not detected as a valid base link (#161)
- as described here https://cq-dev.slack.com/archives/C02DL4SSXCN/p1665735920801589
- www and admin should not be rewritten #145
=> Link Rewrite Fixes

src/forms-pipe.js, test/forms-pipe.test.js
see https://github.com/adobe/helix-html-pipeline/issues/168
=> fix: trim spaces after comma

src/json-pipe.js, test/StaticS3Loader.js, test/json-pipe.test.js
=> fix: handle errors when loading config (1.x)

package-lock.json, package.json, src/steps/parse-markdown.js, src/utils/mdast-to-hast.js
=> feat: use adobe gridtables

src/utils/auth.js, test/utils/auth.test.js
=> fix NPE if auth cookie is expired

src/steps/set-custom-response-headers.js, test/steps/set-custom-headers.test.js
- allows values up to 64k (fixes #204)
- special handling of access-controll-allow-origin (fixes #202)
- allows any custom header (fixes #199)
=> fix: improve custom header handling

src/html-pipe.js
=> Cloudflare url error v1

src/html-pipe.js
=> fix: handle cloudflare url error gracefully (issue #216)

.circleci/config.yml, package-lock.json, src/json-pipe.js, src/steps/set-x-surrogate-key-header.js, test/fixtures/content/one-section/index.md, test/fixtures/content/one-section/index.plain.html, test/json-pipe.test.js, test/rendering.test.js
=> feat: add contentbusId/path as surrogate key

src/steps/fetch-content.js
=> fix: return contentbusId/path surrogate key for redirects

src/forms-pipe.js, src/steps/extract-metadata.js, src/steps/get-metadata.js, src/steps/split-sections.js, src/utils/modifiers.js, src/utils/section-handler.js, test/forms-pipe.test.js, test/markdown-utils.js, test/modifiers.test.js, test/steps/fetch-config-all.test.js, test/steps/get-metadata.test.js
=> fix: prevent prototype pollution

src/steps/fetch-content.js, test/rendering.test.js
=> fix: 404 response should include path-based surrogate key

src/PipelineState.d.ts, src/html-pipe.js, src/steps/authenticate.js, test/steps/authenticate.test.js
=> feat: restrict repositories

src/forms-pipe.js, src/html-pipe.js, src/json-pipe.js, src/steps/fetch-config.js, src/steps/render-code.js, test/forms-pipe.test.js, test/html-pipe.test.js, test/json-pipe.test.js, test/rendering.test.js, test/steps/fetch-config.test.js
- reads the contentBusId from helix-config if missing in query param
- fixes minor bug with missing charset from raw responses (md)
=> fix: read contentbus-id from helix-config

src/html-pipe.js, src/steps/extract-metadata.js, src/steps/fetch-config-all.js, src/steps/fetch-mapped-metadata.js, src/steps/folder-mapping.js, src/steps/set-x-surrogate-key-header.js, test/steps/fetch-config-all.test.js, test/steps/fetch-mapped-metadata.test.js
=> feat: load metadata from mapped path

test/FileS3Loader.js, test/fixtures/content/metadata-product.json, test/rendering.test.js
@tripodsan : just for review, as I had to enhance the `FileS3Loader`
=> chore(test): add test where mapped metadata overwrites global metadata

src/json-pipe.js, test/json-pipe.test.js
=> fix: compute surrogate keys for unfound json

src/utils/auth-cookie.js, test/utils/auth-cookie.test.js
=> fix: use SameSite=None for auth cookie

src/utils/auth-cookie.js, test/utils/auth-cookie.test.js
=> fix: only use SameSite=None for secure cookies

src/html-pipe.js, src/steps/fetch-404.js, src/steps/fetch-content.js, test/rendering.test.js
regression of #307 such as a 404.html would have been requested too early.
=> fix: don't load 404.html too early

src/steps/fetch-404.js, src/steps/set-x-surrogate-key-header.js, test/rendering.test.js
=> fix: properly set surrogate keys for 404 with .plain.html

.nycrc.json, src/steps/utils.js, test/steps/utils.test.js
=> fix: ignore invalid urls in link rewriter

src/json-pipe.js, src/utils/json-filter.js, test/json-pipe.test.js
=> fix: return multisheet for any multisheet query

src/json-pipe.js, test/json-pipe.test.js
=> fix: respect redirects on json pipeline

src/steps/rewrite-icons.js, test/fixtures/content/icons-ignored.html, test/fixtures/content/icons-ignored.md, test/fixtures/content/icons.html, test/fixtures/content/icons.md, test/rendering.test.js
=> fix: ignore urns, hrefs, code blocks for rewrite-icons

src/utils/auth.js, test/utils/auth.test.js
=> fix: respond with 401 for invalid auth config

src/steps/create-page-blocks.js, test/fixtures/content/empty-table-row.html, test/fixtures/content/empty-table-row.md, test/rendering.test.js
=> fix: error with empty html table row

src/options-pipe.js, test/options-pipe.test.js
Pairs well with https://github.com/adobe/franklin-domainkey-provider/pull/35
=> feat(options): add support for domainkey challenges

src/steps/fetch-content.js, test/rendering.test.js
=> fix: append .plain.html in redirects if needed

src/steps/authenticate.js, src/steps/utils.js, src/utils/json-filter.js, test/steps/authenticate.test.js
=> feat: implement partition specific auth

src/steps/set-x-surrogate-key-header.js, test/html-pipe.test.js
=> fix: surrogate key for .md

src/html-pipe.js, src/utils/path.js, test/fixtures/code/my-block.selector.html, test/html-pipe.test.js, test/utils/path.test.js
=> fix: allow static html with selectors

src/steps/set-x-surrogate-key-header.js, src/utils/path.js, test/fixtures/code/my-block.selector.html, test/html-pipe.test.js, test/rendering.test.js, test/sitemap-pipe.test.js, test/utils/path.test.js
- fix: allow static html with selectors (#510)
- feat: remove source-location surrogate key
=> fix: cherry-pick missing 5.x fixes

src/steps/set-x-surrogate-key-header.js, test/rendering.test.js
=> fix: add path key for original path

.github/workflows/main.yaml, src/steps/utils.js, test/steps/utils.test.js
=> feat: improve xfh parsing

package.json, src/json-pipe.js, src/steps/fetch-404.js, src/steps/fetch-content.js, src/steps/set-x-surrogate-key-header.js, test/html-pipe.test.js, test/json-pipe.test.js, test/rendering.test.js, test/sitemap-pipe.test.js
=> Backport surrogate

src/steps/set-x-surrogate-key-header.js, test/html-pipe.test.js, test/rendering.test.js
=> fix: surrogate key for static html

src/steps/fetch-404.js, test/fixtures/code/helix-config.json, test/rendering.test.js
=> fix: add unmapped surrogate key for 404.html (#633)

src/steps/render.js, test/fixtures/content/page-metadata-jsonld-xss.html
=> fix: encode special HTML characters in JSON LD

src/steps/validate-captcha.js, test/steps/validate-captcha.test.js
=> fix: missing config/support should not be treated as 500 (#694)

src/steps/utils.js, test/steps/utils.test.js
=> feat: rewrite same-page links on .plain.html

src/steps/utils.js, test/steps/utils.test.js
=> feat: rewrite same-page links on .plain.html (#656)

src/robots-pipe.js, src/sitemap-pipe.js, test/robots-pipe.test.js, test/sitemap-pipe.test.js
=> fix: adding newline at the end of robots.txt

src/json-pipe.js, src/steps/fetch-404.js, src/steps/fetch-content.js, src/steps/set-x-surrogate-key-header.js, test/json-pipe.test.js, test/rendering.test.js, test/sitemap-pipe.test.js
=> fix: provide either prefixed preview or unprefixed live content keys (DON'T BACKPORT TO V5)

src/steps/fetch-mapped-metadata.js, test/rendering.test.js
=> feat: revert foldermapped last-modified

src/PipelineState.d.ts, src/html-pipe.js, src/steps/extract-metadata.js, src/steps/fetch-mapped-metadata.js, src/steps/folder-mapping.js, test/rendering.test.js, test/steps/fetch-mapped-metadata.test.js
=> fix: apply folder-mapped metadata also for existing resources

.github/workflows/main.yaml
=> fix: run CI on PRs from fork

src/steps/render.js
html lang values need to be case-insensitive.
=> fix(metadata): make html lang case-insensitive

src/sitemap-pipe.js, test/sitemap-pipe.test.js
=> fix(sitemap): helix 5 projects live in aem.page/aem.live
