adobe/helix-html-pipeline

src/forms-pipe.js, test/forms-pipe.test.js
needs for proper user handling in forms-service.
=> fix: include owner and repo in forms message

src/forms-pipe.js, test/forms-pipe.test.js
Forms service expects the `owner` and `repo` to be included as part of the message body. Opted to fix directly in `forms-pipe` rather than in the dispatch method in `SQSMessageDispatcher` as it's not clear to me if other features using SQS pass along `owner` and `repo` to dispatch.
See https://github.com/adobe/helix-forms-service/blob/26e6f880903dc1b5711c3d9266e820bafd1e6efa/src/Utils.js#L139
=> fix: forms service expect repo and owner in message body

src/index.d.ts, src/steps/extract-metadata.js, src/steps/folder-mapping.js, src/utils/path.js, test/fixtures/content/metadata.json, test/rendering.test.js, test/utils/path.test.js
Fixes glob matching for mapped pages
Related Issues
fixes https://github.com/adobe/helix-html-pipeline/issues/69
=> fix: match globs for mapped pages in maintenance pipeline-service

src/steps/create-pictures.js, src/steps/set-custom-response-headers.js, test/fixtures/content/image-from-meta.html, test/fixtures/content/image-no-alt.html, test/fixtures/content/image.html, test/fixtures/content/images.html, test/fixtures/content/meta-response-headers.plain.html, test/fixtures/content/page-block-1-col.html, test/fixtures/content/page-block-1-col.plain.html, test/fixtures/content/page-block-table-in-table.html, test/fixtures/content/page-block-with-html-table.html, test/fixtures/content/stray-p-strong.html, test/fixtures/content/styling.plain.html, test/fixtures/content/unwrap-images.html, test/rendering.test.js
- always use `loading="lazy"` on all img tags
- suppress `link` response headers on .plain.html (and non html)
=> Lazy images

src/utils/json-filter.js, test/utils/json-filter.test.js
In [697](https://github.com/adobe/helix-admin/pull/698) support was added to `preview` workbooks that only contain a `incoming` sheet (no `helix-default`). The result of this is a json file in the content bus with the following data.
```json
{":version":3,":type":"multi-sheet",":names":[]}
```
Currently the pipeline will return a 404 when a `GET` request made on this resource because the `names` property is empty. This PR changes this behaviour to instead return a 200 (including the data). 
A 404 will now only be returned if a sheet filter is explicitly provided in the query params.
The justification for this change is that customers will have a confusing/bad experience when they preview a workbook (with no default sheet) in sidekick and the result is a 404. 
More details in …
=> fix: return 200 with no default sheet, 404 with unmatched sheet filter

src/html-pipe.js, src/json-pipe.js, test/json-pipe.test.js, test/rendering.test.js
fixes #153
- same as #154 for the 1.x branch
- also add headers to the json-pipe (to be done in the main branch)
=> fix(html): do not skip custom headers for 3xx responses

src/utils/auth.js, test/html-pipe.test.js, test/utils/auth.test.js
needed for local development of access controlled projects.
otherwise auth redirect would go to `https://localhost` which is currently not supported.
=> feat: respect x-forwarded-proto in auth

src/utils/auth-cookie.js, src/utils/auth.js, test/utils/auth-cookie.test.js, test/utils/auth.test.js
fastly overrides the `x-forwarded-proto` with a fixed `https` value. so we also add support for `x-forwarded-scheme` header to support localhost development
=> feat: also support x-fwd-scheme

src/steps/utils.js, test/steps/utils.test.js
=> fix: don't rewrite production urls

src/html-pipe.js
Currently floods our coralogix with "errors"
=> fix: log 404 as info

src/html-pipe.js, test/html-pipe.test.js
another occurrence of `log.error` that I missed 🙄
=> fix: use info for response status < 500

src/PipelineState.d.ts, src/PipelineState.js, src/json-pipe.js, src/options-pipe.js, test/fixtures/code/helix-config-head-with-script.json, test/fixtures/code/helix-config-no-head-html.json, test/fixtures/code/helix-config-no-head.json, test/fixtures/code/helix-config.json, test/forms-pipe.test.js, test/html-pipe.test.js, test/json-pipe.test.js, test/options-pipe.test.js, test/rendering.test.js
- remove `contentBusId` from PipelineStateOptions (constructor)
- ensure that `contentBusId` is loaded from helix-config in all pipes
- remove fake contentBusIds from state in tests
=> fix: ensure contentBusId is loaded properly

src/steps/extract-metadata.js, src/steps/render.js, test/fixtures/content/page-metadata-no-fallback.md
metadata block properties that have no value are not rendered, unless they would have a fallback value extracted from the content. in that case, they will have an empty value.
=> fix: supress empty non-fallback values

src/steps/render.js, test/fixtures/content/page-metadata-no-fallback.html
see https://github.com/adobe/helix-pipeline-service/issues/696
=> fix: do not render empty canonical meta tag

src/index.js, src/sitemap-pipe.js, test/fixtures/content/sitemap.xml, test/sitemap-pipe.test.js
fixes #472 partially
this is the first step of implement the dynamic sitemap rendering, by just serving it from content-bus if avaialble.
still todo in a subsequent PR: check if sitemap.json can be loaded and generate the sitemap dynamically.
=> feat: add pipeline for sitemap.xml

src/sitemap-pipe.js, test/sitemap-pipe.test.js
The current output, e.g.:
```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
<url>
<loc>
https://mcqueen-residence.org/
</loc>
<lastmod>2021-09-18</lastmod>
</url>
</urlset>
```
could lead to issues.
=> fix: put <loc> on a single line

src/index.js, src/robots-pipe.js, test/robots-pipe.test.js
To replace the VCL in aem.page/live to return the internal `robots.txt` on preview, inner and outer CDN
=> feat: support dynamic and configurable robots.txt

package-lock.json, src/steps/render.js, test/fixtures/content/no-head-html.html
Update the fallback logic for missing `head.html` to support newer helix projects. 
🚨 Not sure if older projects are utilizing this fallback.
=> fix: remove head fallback

src/steps/fetch-404.js, test/rendering.test.js
=> fix: contentbus-id as surrogate key for 404 response

src/steps/fetch-404.js, test/rendering.test.js
=> fix: add unmapped surrogate key for 404.html

package-lock.json, package.json, src/steps/utils.js, test/steps/utils.test.js
=> Rewrite aem urls

src/steps/fetch-mapped-metadata.js, test/steps/fetch-mapped-metadata.test.js
=> fix: ignore mapped metadata sheet with not default

src/json-pipe.js, test/json-pipe.test.js
=> fix: set code and content surrogate keys for json 404

src/steps/validate-captcha.js, test/steps/validate-captcha.test.js
as discussed to avoid triggering alerts for errors caused by missing configuration or unsupported features
=> fix: missing config/support should not be treated as 500

src/json-pipe.js, test/json-pipe.test.js
=> fix: set code and content surrogate keys for json 404 (#692)

src/json-pipe.js, src/steps/fetch-404.js, src/steps/fetch-content.js, src/steps/set-x-surrogate-key-header.js, test/json-pipe.test.js, test/rendering.test.js, test/sitemap-pipe.test.js
Temporarily provide additional preview content keys (prefixed by `p_`)
Eventually, i.e. once prefixed preview keys have been deployed and admin purge has been changed to purge prefixed keys only on preview,  provide either prefixed preview or unprefixed live content keys.
=> fix: scoped keys for prefix content (DON'T BACKPORT TO V5)

src/steps/rewrite-icons.js, test/fixtures/content/icons-ignored.html, test/fixtures/content/icons-ignored.md, test/fixtures/content/icons.html, test/fixtures/content/icons.md, test/steps/rewrite-icons.test.js
potential regression: if there is no non-word character around the `:icon:`, it will no longer rewrite. eg:
my:smile:is bright.
`Team:rocket:blasting off again`
but github markdown doesn't detect it neither:
my:smile:is bright.
=> fix: avoid icon rewrite of hh:mm:ss and similar

package.json, src/utils/json-filter.js, test/json-pipe.test.js
=> fix: return 400 when code bus JSON has no :names

package-lock.json, package.json, src/PipelineResponse.js, src/html-pipe.js, src/json-pipe.js, src/sitemap-pipe.js, src/steps/fetch-404.js, src/steps/fetch-content.js, src/steps/fetch-mapped-metadata.js, src/steps/init-config.js, src/utils/last-modified.js, test/fixtures/content/generic-product/metadata.json, test/json-pipe.test.js, test/rendering.test.js, test/utils/last-modified.test.js
fixes #743
---
I refactored the last-modified handling a bit, so that each source doesn't update the "best" last modified directly, but only adds a record to the `PipelineResponse.lastModifiedSources` object. so when the applied metadata set contains a last-modified, we can change the `metadata` record.
the "best" (i.e. latest) last modified is then calculated before returning the response.
=> feat: respect last-modified from metadata sheet

src/PipelineState.d.ts, src/html-pipe.js, src/steps/extract-metadata.js, src/steps/fetch-mapped-metadata.js, src/steps/folder-mapping.js, test/rendering.test.js, test/steps/fetch-mapped-metadata.test.js
=> fix: apply folder-mapped metadata also for existing resources

src/forms-pipe.js, test/forms-pipe.test.js
=> fix: check for state.info

src/steps/utils.js, test/steps/utils.test.js
Fixes #767
- [ x] make sure to link the related issues in this description
- [ x] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes
#767
=> Allow canonical URLS to end with `index` but not `/index`

src/steps/utils.js, test/steps/utils.test.js
=> fix: allow canonical URL to end with `index` but not `/index`

src/utils/json-filter.js, test/json-pipe.test.js
=> fix: return columns as well

src/steps/render.js, test/fixtures/content/page-metadata-jsonld-global.html, test/fixtures/content/page-metadata-jsonld-list.html, test/fixtures/content/page-metadata-jsonld-multi.html, test/fixtures/content/page-metadata-jsonld-xss.html, test/fixtures/content/page-metadata-jsonld.html
=> feat: format JSON-LD in response

src/steps/fetch-config.js, test/html-pipe.test.js, test/json-pipe.test.js
the admin sets the `x-created-date` to *now()* for every new branch on its `helix-config.json`. this would cause new branches to fail even on "old" projects.
=> fix: only enforce date-check on main

src/steps/csp.js, test/rendering.test.js
Currently trying to serve a page with nonce CSP results in `500` in cloudflare:
`Worker: x-error: crypto_worker_default2.randomBytes is not a function`
```bash
curl ${CLOUDFLARE_ENDPOINT}/preview/adobe/helix-labs-website/csp-nonce/
< HTTP/2 200 
< date: Thu, 13 Feb 2025 00:28:48 GMT
< content-type: text/html; charset=utf-8
< content-length: 12006
< last-modified: Thu, 13 Feb 2025 00:16:47 GMT
< content-security-policy: script-src 'nonce-MEp9pOJCGw6/rtKRGuKzuLKU' 'strict-dynamic'; base-uri 'self'; object-src 'none';
...
<!DOCTYPE html>
<html>
<head>
<title>Home | Admin Labs</title>
...
<script nonce="MEp9pOJCGw6/rtKRGuKzuLKU" src="/scripts/aem.js" type="module"></script>
<script nonce="MEp9pOJCGw6/rtKRGuKzuLKU" src="/scripts/scripts.js" type="module"></script>
<link rel="stylesheet" …
```
=> fix: Use Web Crypto compatible function for nonce generation - v1

src/steps/set-custom-response-headers.js, test/steps/set-custom-headers.test.js
=> fix: ignore hop-by-hop headers

package-lock.json, src/html-pipe.js, src/steps/fetch-sourced-metadata.js, src/utils/modifiers.js, test/FileS3Loader.js, test/html-pipe.test.js, test/modifiers.test.js
if the metadata section of the config is too large, the config service will not longer include it, but specify the metadata sources. in this case, they are loaded in the html pipeline directly.
see https://github.com/adobe/helix-config/pull/259
=> feat: read metadata directly from source if required

src/steps/utils.js, test/steps/utils.test.js
=> fix: also treat self-ref links to index.plain.html correctly

src/steps/csp.js, test/fixtures/code/super-test/404-csp-nonce.html, test/fixtures/code/super-test/static-nonce-meta-move-as-header.html, test/rendering.test.js
This PR contains two changes:
- Renaming `"move-as-header"` to `"move-to-http-header"` as requested by David, to make it more clear what it does
- We have to keep the old name until I migrate the early adopters, so after migrating them, I'll come back to cleanup
- Allow `"move-to-http-header"` only for `nonce-aem` based CSP, because that's the only way we support it for the static HTMLs.
=> fix: Rename "move-as-header" to "move-to-http-header"
